services:
  - type: web
    name: quotastro-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python value_bot_allinone.py bot
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: API_FOOTBALL_KEY
        sync: false
